version: '3'
services:
  postgres:
    image: postgres:9.4-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
  elasticsearch:
    #image: nickstenning/elasticsearch-icu
    image: elasticsearch:2.4-alpine
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - '127.0.0.1:9200:9200'
  redis:
    image: redis:4.0.1
    ports:
        - '127.0.0.1:6379:6379'
    volumes:
      - ./redis_data:/data
